#!/bin/bash
# Regenerate the bundled pricing catalog from the published feed source.
#
# docs/pricing.json is the single source of truth for prices. It is served to
# installed apps over HTTPS, and embedded here so a fresh install (or one that
# can't reach the network) still prices usage correctly offline.
#
# Run after editing docs/pricing.json. CI fails if the generated file is stale.
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FEED="$REPO_DIR/docs/pricing.json"
GENERATED="$REPO_DIR/Sources/ClaudeCodeUsageKit/Pricing/BundledPricingFeed.swift"

if ! python3 -c "import json,sys; json.load(open(sys.argv[1]))" "$FEED"; then
    echo "error: $FEED is not valid JSON" >&2
    exit 1
fi

# The JSON is embedded as a Swift raw string literal, so it must not contain the
# closing delimiter.
if grep -q '"""#' "$FEED"; then
    echo "error: $FEED contains the raw-string delimiter '\"\"\"#'" >&2
    exit 1
fi

{
    echo '// Generated by Scripts/embed_pricing.sh from docs/pricing.json.'
    echo '// Do not edit. Edit docs/pricing.json and re-run the script.'
    echo
    echo 'import Foundation'
    echo
    echo '// MARK: - Pricing shipped inside the app'
    echo
    echo '/// The feed as published when this build was cut. Used on first launch'
    echo '/// and whenever the live feed is unreachable or invalid.'
    echo 'enum BundledPricingFeed {'
    # Emitted verbatim at column 0: a Swift multiline literal strips the closing
    # delimiter's indentation, so column 0 keeps the JSON byte-identical to the feed.
    echo '    static let json = #"""'
    cat "$FEED"
    echo '"""#'
    echo
    echo '    /// Decoded once. The generated JSON is validated by CI, so a failure'
    echo '    /// here means this file was hand-edited instead of regenerated.'
    echo '    static let catalog: PricingCatalog = {'
    echo '        guard let data = json.data(using: .utf8),'
    echo '              let decoded = try? PricingCatalogDecoder.decode(data, origin: .bundled)'
    echo '        else {'
    echo '            preconditionFailure('
    echo '                "BundledPricingFeed.json is not a valid pricing feed. Run Scripts/embed_pricing.sh.")'
    echo '        }'
    echo '        return decoded'
    echo '    }()'
    echo '}'
} > "$GENERATED"

echo "Generated $GENERATED from $FEED"
